<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DotNetRepoInspector.Mcp.Performance</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/DotNetRepoInspector.Cli/DotNetRepoInspector.Cli.csproj" />
    <ProjectReference Include="../../src/DotNetRepoInspector.Engine/DotNetRepoInspector.Engine.csproj" />
    <ProjectReference Include="../../src/DotNetRepoInspector.Mcp/DotNetRepoInspector.Mcp.csproj" />
  </ItemGroup>
</Project>
