<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>DotNetRepoInspector.Persistence.Http.Tests</RootNamespace>
    <AssemblyName>DotNetRepoInspector.Persistence.Http.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.MTP" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" PrivateAssets="all" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/DotNetRepoInspector.Core/DotNetRepoInspector.Core.csproj" />
    <ProjectReference Include="../../src/DotNetRepoInspector.Persistence/DotNetRepoInspector.Persistence.csproj" />
    <ProjectReference Include="../../src/DotNetRepoInspector.Persistence.Http/DotNetRepoInspector.Persistence.Http.csproj" />
  </ItemGroup>
</Project>
