<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DotNetRepoInspector.Git</RootNamespace>
    <AssemblyName>DotNetRepoInspector.Git</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DotNetRepoInspector.Core/DotNetRepoInspector.Core.csproj" />
  </ItemGroup>
</Project>
